version: '3'
services:
  postgres:
    image: "postgres:latest"
    
    ports:
      # N.B. format is [port on machine]:[port to expose from container]
      - 5432:5432

    environment: 
      POSTGRES_USER: synapse_user
      POSTGRES_PASSWORD: synapse_pass
      POSTGRES_DB: synapse
      PGDATA: /tmp/data

    volumes:
      - ./database_setup.sh:/docker-entrypoint-initdb.d/1_database_setup.sh 

    tmpfs:
      /tmp/data
